# Generated by Django 3.1.1 on 2020-11-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleeperApp', '0002_gamelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelogs',
            name='all_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='catch_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='def_int',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='def_int_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='def_int_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='def_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fg_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fga',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fgm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_forced',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_lost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_rec',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_rec_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_rec_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='game_location',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='gs',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='kick_ret',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='kick_ret_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='kick_ret_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='kick_ret_yds_per_ret',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='off_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='offense',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_adj_yds_per_att',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_att',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_cmp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_cmp_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_defended',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_int',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_sacked',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_sacked_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_yds_per_att',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_blocked',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_ret',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_ret_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_ret_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_ret_yds_per_ret',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='punt_yds_per_punt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='qb_hits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec_yds_per_rec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec_yds_per_tgt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rush_att',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rush_td',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rush_yds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rush_yds_per_att',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='sacks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='safety_md',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='scoring',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='special_teams',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='st_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='tackles_assists',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='tackles_combined',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='tackles_loss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='tackles_solo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='targets',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='two_pt_md',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='xp_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='xpa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='xpm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
