# Generated by Django 3.1.1 on 2020-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleeperApp', '0003_auto_20201106_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelogs',
            name='fumbles_rec_yds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_sacked_yds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='pass_yds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rec_yds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogs',
            name='rush_yds',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
